### ISSUE TITLE
Missing update on kickstarter

### ISSUE THREAD

**Issue by rabsef-bicrym** [RocketGod-git/cyper-pro#1]
Haven't seen an update for a while. Figure y'all forgot to kill this repo. Embarrassing

**Comment by RocketGod-git** [comment]
I have nothing to do with them. I was just planning on porting my Flipper Zero repo for this device if it actually was manufactured. 

Unfortunately it was a scam.

**Comment by rabsef-bicrym** [comment]
Fair cop - my bad.
